### ISSUE TITLE
It doesn't see second SIM card.

### ISSUE THREAD

**Issue by vi** [yeriomin/DumbphoneAssistant#4]

**Comment by yeriomin** [comment]
Unfortunately, SIM-related android interface is old and vendor-specific. Changes for dual-sim support in Android 5.1 didn't touch SIM contacts and SIM SMS. The API I'm using hasn't changed since Android 2.0.

Getting/putting contacts from/to an arbitrary SIM card is and will probably always be impossible. Only the main SIM card will be seen.

**Comment by vi** [comment]
Probably you mean "impossible with a documented API" or "impossible without root access or vendor-specific APIs".

**Comment by yeriomin** [comment]
Right.

**Comment by PanderMusubi** [comment]
What is the exact API (plus documentation) that is being used? Has supporting multi SIM improved nowadays?
