### ISSUE TITLE
Does not copy contacts with '+' for international code

### ISSUE THREAD

**Issue by DevilMindRex** [yeriomin/DumbphoneAssistant#5]
Does not copy contacts with '+'  in begging for international code.
Example number +92 344 1000200 will not copy, but 0344 1000200 will copy, also 0092 344 1000200 works also.

Solution to this problem:
Add option to convert +92 344 1000200 to 0092 344 1000200, Do not +92 344 1000200 to 92 344 1000200 as removing '+' makes the number USELESS for calls, SMS or other apps.

Thank you awaiting your response

**Comment by yeriomin** [comment]
Thank you for your feedback, but I can not reproduce the issue. Copying this number from and to sim card worked fine. Would appreciate any more specific steps to reproduce it.

There is no filtering of + character in the app (on purpose at least).

Unfortunately, the solution you suggested would not work because international exit codes differ from country to country and even operator to operator. It would be impossible to replace + with a proper code without having a phone number db. Check this link: http://www.howtocallabroad.com/qa/plus-sign.html

**Comment by PanderMusubi** [comment]
It works for me too. Perhaps delete the spaces in the numbers.
